### Obtener todos los personajes
GET http://localhost:3000/api/characters

### Obtener un personaje por ID
GET http://localhost:3000/api/characters/85d643b6-6273-4d56-acfb-b38ad4246f07
### Borrar por ID
DELETE http://localhost:3000/api/characters/1330f722-07df-4a72-bd89-dadf8179d2ce

### Crear un nuevo personaje
//Tener cuidado con la extra linea desp de content-type
POST http://localhost:3000/api/characters   
Content-Type: application/json 

{
  "name": "Tingle",
  "characterClass": "Fairy",
  "level": 1,
  "hp": 10,
  "mana": 500,
  "attack": 10,
  "items": ["Wand", "Maps"],
  "id": "randomUUID()"
}

### Actua un personaje por ID solo algunos atb
PATCH http://localhost:3000/api/characters/883101a6-e353-4c6a-9558-1470d619da7b
Content-Type: application/json

{
  "level": 3,
  "hp": 150,
  "mana": 150,
  "attack": 150
}

### Actua un personaje por ID al 100%
PUT http://localhost:3000/api/characters/3d41f377-b33e-46-9906-9f82ce9d5d9c
Content-Type: application/json

{
  "name": "Ganon",
  "characterClass": "Beast",
  "level": 3,
  "hp": 150,
  "mana": 150,
  "attack": 150,
  "items": ["Super Sword", "Ganon's Shield"]
}

