### Obtener todos los personajes
GET http://localhost:3000/api/characters
### Obtener un personaje por ID
GET http://localhost:3000/api/characters/2860e5b1-92cf-4efb-92a5-23dec9b0ffb9

### Crear un nuevo personaje
//Tener cuidado con la extra linea desp de content-type
POST http://localhost:3000/api/characters
Content-Type: application/json 

{
  "name": "Tingle",
  "characterClass": "Fairy",
  "level": 1,
  "hp": 10,
  "mana": 500,
  "attack": 10,
  "items": ["Wand", "Maps"],
  "id": "randomUUID()"
}

### Actua un personaje por ID
PUT http://localhost:3000/api/characters/b65066a2-b3ee-4fe4-9d08-694802a7c3b2
Content-Type: application/json

{
  "name": "Ganon",
  "characterClass": "Beast",
  "level": 3,
  "hp": 150,
  "mana": 150,
  "attack": 150,
  "items": ["Super Sword", "Ganon's Shield"]
}